{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "To μηδέν αναπαριστά το κενό\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "πάνω αριστερά 3\n",
      "πάνω 5\n",
      "πάνω δεξια 4\n",
      "αριστερά 7\n",
      "κέντρο 6\n",
      "δεξιά 8\n",
      "κάτω αριστερά 0\n",
      "κάτω 1\n",
      "κάτω δεξιά 2\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[3, 5, 4, 7, 6, 8, 0, 1, 2]\n",
      "68\n",
      "132\n",
      "195\n",
      "235\n",
      "299\n",
      "367\n",
      "448\n",
      "502\n",
      "579\n",
      "622\n",
      "654\n",
      "702\n",
      "760\n",
      "[0, 'right', 'right', 'up', 'left', 'down', 'left', 'up', 'right', 'down', 'right', 'up', 'up', 'left', 'left', 'down', 'right', 'right', 'up', 'left', 'left', 'down', 'right', 'right', 'down', [1, 2, 3, 4, 5, 6, 7, 8, 0]]\n"
     ]
    }
   ],
   "source": [
    "Arx=[] # The possible states are represented by a list\n",
    "Telos=[1,2,3,4,5,6,7,8,0] #The goal state\n",
    "print('To μηδέν αναπαριστά το κενό') #Zero represents the space\n",
    "Arx.append(int(input('πάνω αριστερά'))) # The user gives the initial state, the first element corresponds to the upper left piece\n",
    "Arx.append(int(input('πάνω'))) #the second element corresponds to the upper piece\n",
    "Arx.append(int(input('πάνω δεξια')))#the third element corresponds to the upper right piece\n",
    "Arx.append(int(input('αριστερά'))) #the fourth element corresponds to the left piece...\n",
    "Arx.append(int(input('κέντρο')))\n",
    "Arx.append(int(input('δεξιά')))\n",
    "Arx.append(int(input('κάτω αριστερά')))\n",
    "Arx.append(int(input('κάτω')))\n",
    "Arx.append(int(input('κάτω δεξιά')))\n",
    "\n",
    "print(Arx) #Prints start state\n",
    "mesi=Arx.copy() #Makes a copy of the initial state\n",
    "\n",
    "def up(mesi):  # The action 'move the space up' is emulated by a function\n",
    "    mesi_u=mesi.copy() \n",
    "    if 0 in mesi[3:9]: # If the space is not in the upper line, it will be executed \n",
    "        thesikeno=mesi.index(0) #finds where the zero is\n",
    "        mesi_u[thesikeno]=mesi[thesikeno-3] # changes the value of the space brick with the above it\n",
    "        mesi_u[thesikeno-3]=0 #and the one above with 0\n",
    "    else:#If the space is in the upper line, it won't be executed \n",
    "        pass\n",
    "    return mesi_u\n",
    "def down(mesi): # The action down\n",
    "    mesi_d=mesi.copy()\n",
    "    if 0 in mesi[0:6]:\n",
    "        thesikeno=mesi.index(0)\n",
    "        mesi_d[thesikeno]=mesi[thesikeno+3]\n",
    "        mesi_d[thesikeno+3]=0\n",
    "    else:\n",
    "        pass\n",
    "    return mesi_d\n",
    "def right(mesi): # The action right\n",
    "    mesi_r=mesi.copy()\n",
    "    if mesi[2]!=0 and mesi[5]!=0 and mesi[8]!=0:\n",
    "        thesikeno=mesi.index(0)\n",
    "        mesi_r[thesikeno]=mesi[thesikeno+1]\n",
    "        mesi_r[thesikeno+1]=0\n",
    "    else:\n",
    "        pass\n",
    "    return mesi_r\n",
    "def left(mesi): # The action left\n",
    "    mesi_l=mesi.copy()\n",
    "    if mesi[0]!=0 and mesi[3]!=0 and mesi[6]!=0:\n",
    "        thesikeno=mesi.index(0)\n",
    "        mesi_l[thesikeno]=mesi[thesikeno-1]\n",
    "        mesi_l[thesikeno-1]=0\n",
    "    else:\n",
    "        pass\n",
    "    return mesi_l\n",
    "        \n",
    "def ektim(mesi): #An admissible heuristic (Manhatan distance)\n",
    "    ektim=0\n",
    "    for i in range(1,9): #For every piece\n",
    "        ektim+=abs(mesi.index(i)//3-(i-1)//3)+abs(mesi.index(i)%3-(i-1)%3) # The distance in colums and rows of the ideal and current position\n",
    "    return ektim\n",
    "\n",
    "diadromi={0:[ektim(mesi),mesi]} #The search tree search. A key, evaluation, the action sequence(cannot be seen), and the state\n",
    "fylla=[[ektim(mesi)+0,mesi,0,0]] #Leave nodes. Evaluation plus steps to reach the node(A*), the state, the key, and the parent node\n",
    "palies=[mesi] #Visited states\n",
    "\n",
    "def elax(fylla): # Finds the minimum evaluation\n",
    "    elaxi=[]\n",
    "    for i in range(len(fylla)):\n",
    "        elaxi.append(fylla[i][0])\n",
    "    return min(elaxi)\n",
    "\n",
    "def epilogi(fylla): #chooses the firt node of the leave nodes with evaluation equal to the minimum\n",
    "    i=0\n",
    "    while i<len(fylla):\n",
    "        if fylla[i][0]==elax(fylla):\n",
    "            break\n",
    "        i+=1\n",
    "    return i\n",
    "            \n",
    "\n",
    "def ekser(fylla,i): #expands the optimal node\n",
    "    kratoymeno=1 \n",
    "    a=diadromi[fylla[i][2]].copy()\n",
    "    b=diadromi[fylla[i][2]].copy()\n",
    "    c=diadromi[fylla[i][2]].copy()\n",
    "    d=diadromi[fylla[i][2]].copy()\n",
    "    if up(fylla[i][1])!=fylla[i][1] and fylla[i][3]!=1 and up(fylla[i][1]) not in palies:#if acion up has efect and doesn't return to state that is explored\n",
    "        a[-1]=up(fylla[i][1]) \n",
    "        a[0]=ektim(up(fylla[i][1]))\n",
    "        a.insert(-1,\"up\")\n",
    "        diadromi[fylla[i][2]]=a # Add the new state to the memory\n",
    "        palies.append(up(fylla[i][1]))\n",
    "        neaolekt=fylla[i][0]+ektim(up(fylla[i][1]))-ektim(fylla[i][1])+1 #changes the new total evaluation of the new state\n",
    "        fylla.append([neaolekt,up(fylla[i][1]),fylla[i][2],2])\n",
    "        kratoymeno=0\n",
    "    else:\n",
    "        pass\n",
    "    if down(fylla[i][1])!=fylla[i][1] and fylla[i][3]!=2 and down(fylla[i][1]) not in palies:\n",
    "        b[-1]=down(fylla[i][1])\n",
    "        b[0]=ektim(down(fylla[i][1]))\n",
    "        b.insert(-1,\"down\")\n",
    "        palies.append(down(fylla[i][1]))\n",
    "        neaolekt=fylla[i][0]+ektim(down(fylla[i][1]))-ektim(fylla[i][1])+1\n",
    "        if kratoymeno==0:\n",
    "            fylla.append([neaolekt,down(fylla[i][1]),len(diadromi),1])\n",
    "            diadromi[len(diadromi)]=b\n",
    "        else:\n",
    "            diadromi[fylla[i][2]]=b\n",
    "            fylla.append([neaolekt,down(fylla[i][1]),fylla[i][2],1])\n",
    "            kratoymeno=0\n",
    "    else:\n",
    "        pass\n",
    "    if right(fylla[i][1])!=fylla[i][1] and fylla[i][3]!=3 and right(fylla[i][1]) not in palies:\n",
    "        c[-1]=right(fylla[i][1])\n",
    "        c[0]=ektim(right(fylla[i][1]))\n",
    "        c.insert(-1,\"right\")\n",
    "        palies.append(right(fylla[i][1]))\n",
    "        neaolekt=fylla[i][0]+ektim(right(fylla[i][1]))-ektim(fylla[i][1])+1\n",
    "        if kratoymeno==0:\n",
    "            fylla.append([neaolekt,right(fylla[i][1]),len(diadromi),4])\n",
    "            diadromi[len(diadromi)]=c\n",
    "        else:\n",
    "            fylla.append([neaolekt,right(fylla[i][1]),fylla[i][2],4])\n",
    "            diadromi[fylla[i][2]]=c\n",
    "            kratoymeno=0\n",
    "    else:\n",
    "        pass\n",
    "    if left(fylla[i][1])!=fylla[i][1] and fylla[i][3]!=4 and left(fylla[i][1]) not in palies:\n",
    "        d[-1]=left(fylla[i][1])\n",
    "        d[0]=ektim(left(fylla[i][1]))\n",
    "        d.insert(-1,\"left\")\n",
    "        palies.append(left(fylla[i][1]))\n",
    "        neaolekt=fylla[i][0]+ektim(left(fylla[i][1]))-ektim(fylla[i][1])+1\n",
    "        if kratoymeno==0:\n",
    "            fylla.append([neaolekt,left(fylla[i][1]),len(diadromi),3])\n",
    "            diadromi[len(diadromi)]=d\n",
    "        else:\n",
    "            fylla.append([neaolekt,left(fylla[i][1]),fylla[i][2],3])\n",
    "            diadromi[fylla[i][2]]=d \n",
    "    else:\n",
    "        pass\n",
    "    del fylla[i]\n",
    "    return fylla\n",
    "\n",
    "i=0\n",
    "while len(fylla)>0 and Telos not in palies[-4:]: #While Goal state not found (and the tree is not completly searched)\n",
    "    ekser(fylla,epilogi(fylla)) #expand the optimal leave node\n",
    "    i+=1\n",
    "    if i%100==0: #Print once in a while how many leave are\n",
    "        print(len(fylla))\n",
    "    \n",
    "\n",
    "def teleiwsame(fylla): # find the goal state in the leaves\n",
    "    j=0\n",
    "    while j<len(fylla):\n",
    "        if fylla[j][1]==Telos:\n",
    "            break\n",
    "        else:\n",
    "            pass\n",
    "        j+=1\n",
    "    return fylla[j][2] #And give the the key\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "print(diadromi[teleiwsame(fylla)]) #use the Key to print the sequence\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
